sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - deps=""

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3

before_install:
  - composer self-update

install:
  - if [ "$PACKAGES" != "" ]; then composer require --no-update $PACKAGES; fi
  - composer update $COMPOSER_OPTIONS
